### ISSUE TITLE
Promoting this repo to codeclimate org?

### ISSUE THREAD

**Issue by maxjacobson** [jpignata/codeclimate-markdownlint#13]
Hey @jpignata!

WDYT about moving this repo to the codeclimate org on GitHub? We'd like to make some fixes for #11 and #12 and cut a new release. We're happy to take over maintaining the repo or just make PRs against it here, whichever your prefer.

**Comment by jpignata** [comment]
Hey @maxjacobson! Good to meet you.

Happy to get this transferred to the codeclimate org so you aren't waiting for me to move the engine forward. I just added you as a collaborator. Let me know if you need anything from me to forklift the repo.

**Comment by maxjacobson** [comment]
@jpignata nice to meet you too!

Thanks for adding me as a collaborator. It looks like I have write but not admin access, so I can't transfer the repo.

Whenever you have time, will you either initiate the transfer by following the steps [here](https://help.github.com/articles/transferring-a-repository-owned-by-your-personal-account/#transferring-to-an-organization) or bump my access level to admin?

Thanks for your help!

**Comment by jpignata** [comment]
Well, since I'm not an administrator of the codeclimate org, I cannot initiate a transfer myself.

I just transferred it to you – presumably you can accept the transfer and then move it into codeclimate. Let me know if I need to take any further action.

**Comment by maxjacobson** [comment]
@jpignata nope, all done. Thank you very much for your help
