### ISSUE TITLE
Might not find files in sub-directories

### ISSUE THREAD

**Issue by pbrisbin** [jpignata/codeclimate-markdownlint#4]
Reading [this code](https://github.com/jpignata/codeclimate-markdownlint/blob/master/lib/cc/engine/markdownlint.rb#L36), it looks like the engine takes `include_paths` and `select`s out entries ending in `.md` -- what about directory entries?

I have not tested this (yet), but I suspect `include_paths: ["docs/"]` wouldn't work.

**Comment by pbrisbin** [comment]
Sorry, I see #1 now. I might've considered that blocking before https://github.com/codeclimate-community/submissions/pull/50 was opened though.

**Comment by jpignata** [comment]
@pbrisbin Thanks. I opened up that pull to bait the machinery of code review. We'll get the engine-specific issues sorted here before moving forward on that other pull.
