### ISSUE TITLE
Configuring rules

### ISSUE THREAD

**Issue by wjdp** [jpignata/codeclimate-markdownlint#6]
Is there a current way to specify rules? I've tried a `.mdlrc` file in the project root but CC doesn't seem to pick up.

**Comment by jpignata** [comment]
Hey @wjdp! Not currently – I punted on this. I'm going to add this feature over the next few days though and ship a new version.

**Comment by afeld** [comment]
Ha, I was literally just looking into this. It appears that [Markdownlint is looking in `~/.mdlrc`](https://github.com/mivok/markdownlint/blob/b098cdbc15fc478956cc78e51bafb56bfc60a54f/lib/mdl/cli.rb#L17-L21), so it may be a matter of passing a `--config /code/.mdlrc` option if that file exists.

/cc https://github.com/mivok/markdownlint/issues/123

**Comment by jpignata** [comment]
Right on. I'll do a pass on this, and look into what other command line flags should be supported via the `config` stanza.

**Comment by jpignata** [comment]
@afeld @wjdp I just merged a pull to honor the `.mdlrc` file – if I ship this would that solve your issue?

**Comment by wjdp** [comment]
Yep, pretty sure it will

**Comment by jpignata** [comment]
Great. Shipping this out this evening.
